### ISSUE TITLE
Add text

### ISSUE THREAD

**Issue by A29-Dev** [SeeSharpeDen/miitopia#13]
Ability to specify top and bottom text to be added to the meme. 

Example:

@miitopia [URL] [top=Top Text] [bottom=bottom text] [impact] [border = black] [fill = white]

**Comment by nin-jat** [comment]
That's going a bit out of scope for a discord bot that adds music to images.

Maybe suitable for clippy or a seperate discord bot.

There's a few great projects you could use to get the ball rolling.

There's RawNeatball's [meme-cli](https://github.com/TheRawMeatball/meme-cli) and the [template repo](https://github.com/TheRawMeatball/memeinator-memesrc). The templates used in meme-cli are simple json. The actual meme generation is a seperate crate and could be incorporated into a discord bot.

There's also https://github.com/cmdrkeene/memegen
